#! /bin/bash

Linklist:main.o exitFunc.o init.o mainMenu.o createLinklist.o createNode.o insertNode.o deleteNode.o displayNode.o insertBeg.o insertEnd.o insertKey.o insertNth.o insertMenu.o deleteBeg.o deleteEnd.o deleteNth.o deleteKey.o deleteMenu.o deleteKth.o insertKth.o sortNode.o
	gcc -o Linklist main.o exitFunc.o init.o mainMenu.o createLinklist.o createNode.o insertNode.o deleteNode.o displayNode.o insertBeg.o insertEnd.o insertKey.o insertNth.o insertMenu.o deleteBeg.o deleteEnd.o deleteNth.o deleteKey.o deleteMenu.o deleteKth.o insertKth.o sortNode.o


main.o:main.c header.h declaration.h
	gcc -c main.c
exitFunc.o:exitFunc.c header.h declaration.h
	gcc -c exitFunc.c
init.o:init.c header.h declaration.h
	gcc -c init.c
mainMenu.o:mainMenu.c header.h declaration.h
	gcc -c mainMenu.c
createLinklist.o:createLinklist.c header.h declaration.h
	gcc -c createLinklist.c
createNode.o:createNode.c header.h declaration.h
	gcc -c createNode.c
insertNode.o:insertNode.c header.h declaration.h
	gcc -c insertNode.c
deleteNode.o:deleteNode.c header.h declaration.h
	gcc -c deleteNode.c
displayNode.o:displayNode.c header.h declaration.h
	gcc -c displayNode.c
insertBeg.o:insertBeg.c header.h declaration.h
	gcc -c insertBeg.c
insertEng.o:insertEng.c header.h declaration.h
	gcc -c insertEng.c
insertKey.o:insertKey.c header.h declaration.h
	gcc -c insertKey.c
insertNth.o:insertNth.c header.h declaration.h
	gcc -c insertNth.c
insertKth.o:insertKth.c header.h declaration.h
	gcc -c insertKth.c
deleteBeg.o:deleteBeg.c header.h declaration.h
	gcc -c deleteBeg.c
deleteEng.o:deleteEng.c header.h declaration.h
	gcc -c deleteEng.c
deleteKey.o:deleteKey.c header.h declaration.h
	gcc -c deleteKey.c
deleteNth.o:deleteNth.c header.h declaration.h
	gcc -c deleteNth.c
deleteKth.o:deleteKth.c header.h declaration.h
	gcc -c deleteKth.c
insertMenu.o:insertMenu.c header.h declaration.h
	gcc -c insertMenu.c
deleteMenu.o:deleteMenu.c header.h declaration.h
	gcc -c deleteMenu.c
sortNode.o:sortNode.c header.h declaration.h
	gcc -c sortNode.c
